version: "3.7"

services:
  ws-proxy:
    build:
      context: .
      target: ws_proxy
    image: afeoscyc-mw.cec.lab.emc.com/devops/ws-proxy:latest
    command:  gunicorn app.main:app --workers=3 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
#    ports:
#      - "8000:8000"
    restart: always
    depends_on:
      - redis
      - nginx
    networks:
      - backend

  test:
    build:
      context: .
      target: ws_test
    depends_on:
      - redis
    networks:
      - backend
    command: pytest --cov=app --cov-fail-under 100 --cov-report term-missing -v -s

  nginx:
    build: ./nginx
    volumes:
      - /etc/ssl:/etc/ssl
    ports:
      - "86:80"
      - "9443:9443"
    networks:
      - backend
    restart: always

  redis:
    image: redis
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    command: redis-server --appendonly yes
    restart: always


networks:
  backend:
