version: "2.0"

services:
  ws-proxy:
    build:
      context: .
    command:  gunicorn app.main:app --workers=3 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
#    ports:
#      - "8000:8000"
    restart: always
    networks:
      - backend

  nginx:
    build: ./nginx
    volumes:
      - /etc/ssl:/etc/ssl
    ports:
      - "86:80"
      - "9443:9443"
    networks:
      - backend
    depends_on:
      - ws-proxy
    restart: always

networks:
  backend:
